### ISSUE TITLE
SHA256 Example, Exception in Java parser

### ISSUE THREAD

**Issue by HSG88** [pepper-project/pequin#13]
Hi
I'm trying to play with SHA256, so I wrote example where the input is a message and the output is SHA256 digest. However when I try to run the sample, it compiles successfully, but it throws runtime exception in Java parser

> BUILD SUCCESSFUL
Total time: 0 seconds
make[1]: Leaving directory '/home/hisham/Coding/pequin/compiler/frontend'
WARNING: --cstdarithtruncate is disabled, so type errors will warn and arithmetic is not ANSI C compliant
Compiling test.c
Exception in thread "main" java.lang.RuntimeException: I don't know how to parse declarator [].
	at ccomp.parser.CParser$130.reduce(CParser.java:1172)
	at ccomp.parser.CParser.invokeReduceAction(CParser.java:1756)
	at beaver.Parser.reduce(Parser.java:464)
	at beaver.Parser.parse(Parser.java:383)
	at beaver.Parser.parse(Parser.java:352)
	at ccomp.parser_hw.CCompiler.compileProgram(CCompiler.java:163)
	at zcc.ZCC.compile(ZCC.java:230)
	at zcc.ZCC.main(ZCC.java:127)
Makefile:115: recipe for target 'bin/test.params' failed
make: *** [bin/test.params] Error 1

The code sample 
`#include <stdint.h>
#include<sha256.h>
#define BLOCKSIZE 64
#define HASHSIZE 32
struct In { unsigned char message[BLOCKSIZE]; };
struct Out { unsigned char hash[HASHSIZE]; };
void sha256(int len, unsigned char *input, unsigned char *hash) {
  SHA256_CTX ctx;
  sha256_init(&ctx);
  sha256_update(&ctx, input, len);
  sha256_final(&ctx, hash);
}
void compute(struct In *input, struct Out *output){
int len =BLOCKSIZE;
sha256(len, input->message, output->hash);
}`

I copied sha256.c and sha256.h to pequin/compiler/cstdinc. 

Thanks for your help in advance

**Comment by maxhowald** [comment]
Where did you get sha256.c and sha256.h from? It looks like there is some C99 construct in those files that our compiler doesn't understand.

Unfortunately, we don't support a lot of C99, so most of the time just copying code meant for ordinary compilers won't work very well.

So you could either modify the SHA-256 implementation you have, or implement it yourself in C89 style.

As an example of this, you can look at pequin/pepper/apps/sha_1.c for an implementation of SHA-1.

**Comment by HSG88** [comment]
I found them under the directory pequin/pepper/common

**Comment by cnasikas** [comment]
Hi

I am also trying to compile a SHA256 implementation and I face various problems.

Implementations:

- https://github.com/B-Con/crypto-algorithms/blob/master/sha256.c

- https://github.com/openssl/openssl/blob/master/crypto/sha/sha256.c

- https://github.com/pepper-project/pequin/blob/master/pepper/common/sha256.cpp

Problems:

- string.h,<openssl/sha.h>, <stdlib.h>, <memory.h> can not be found. 
   Error: No such file or directory

- Parser error: I don't know how to parse declarator []

Why those libraries can not be included despite being installed in the system (i.e. libssl-deb)? The [] declarator is mentioned for the arrays inside the functions ?

I understand that the compiler understand C89 style and the above implementations are not. I would be nice to have a SHA256 implementation. Any help would be appreciate.

Thanks in advanced

**Comment by cnasikas** [comment]
I also compiled this implementation:

https://github.com/B-Con/crypto-algorithms/blob/master/sha256.c

with gcc sha256.c -std=c89 and everything compiles fine (after removing the non C89 comments)

**Comment by cnasikas** [comment]
I am posting a successful implementation that compiles based on: 

https://github.com/pepper-project/pequin/blob/master/pepper/common/sha256.cpp

```
#include <stdio.h>

#define uchar unsigned char
#define uint unsigned long

struct In {
  int digest;
};

struct Out {
  int valid;
  unsigned char buf[32];
};

#define DBL_INT_ADD(a,b,c) if (a > 0xffffffff - (c)) ++b; a += c;
#define ROTLEFT(a,b) (((a) << (b)) | ((a) >> (32-(b))))
#define ROTRIGHT(a,b) (((a) >> (b)) | ((a) << (32-(b))))

#define CH(x,y,z) (((x) & (y)) ^ (~(x) & (z)))
#define MAJ(x,y,z) (((x) & (y)) ^ ((x) & (z)) ^ ((y) & (z)))
#define EP0(x) (ROTRIGHT(x,2) ^ ROTRIGHT(x,13) ^ ROTRIGHT(x,22))
#define EP1(x) (ROTRIGHT(x,6) ^ ROTRIGHT(x,11) ^ ROTRIGHT(x,25))
#define SIG0(x) (ROTRIGHT(x,7) ^ ROTRIGHT(x,18) ^ ((x) >> 3))
#define SIG1(x) (ROTRIGHT(x,17) ^ ROTRIGHT(x,19) ^ ((x) >> 10))

typedef struct {
  uchar data[64];
  uint datalen;
  uint bitlen[2];
  uint state[8];
} SHA256_CTX;

uint sha256_key[64] = {
  0x428a2f98,0x71374491,0xb5c0fbcf,0xe9b5dba5,0x3956c25b,0x59f111f1,0x923f82a4,0xab1c5ed5,
  0xd807aa98,0x12835b01,0x243185be,0x550c7dc3,0x72be5d74,0x80deb1fe,0x9bdc06a7,0xc19bf174,
  0xe49b69c1,0xefbe4786,0x0fc19dc6,0x240ca1cc,0x2de92c6f,0x4a7484aa,0x5cb0a9dc,0x76f988da,
  0x983e5152,0xa831c66d,0xb00327c8,0xbf597fc7,0xc6e00bf3,0xd5a79147,0x06ca6351,0x14292967,
  0x27b70a85,0x2e1b2138,0x4d2c6dfc,0x53380d13,0x650a7354,0x766a0abb,0x81c2c92e,0x92722c85,
  0xa2bfe8a1,0xa81a664b,0xc24b8b70,0xc76c51a3,0xd192e819,0xd6990624,0xf40e3585,0x106aa070,
  0x19a4c116,0x1e376c08,0x2748774c,0x34b0bcb5,0x391c0cb3,0x4ed8aa4a,0x5b9cca4f,0x682e6ff3,
  0x748f82ee,0x78a5636f,0x84c87814,0x8cc70208,0x90befffa,0xa4506ceb,0xbef9a3f7,0xc67178f2
};

void sha256_init(SHA256_CTX *ctx);
void sha256_update(SHA256_CTX *ctx, uchar *data, uint len);
void sha256_final(SHA256_CTX *ctx, uchar *hash);

void sha256_transform(SHA256_CTX *ctx, uchar *data) {
  uint a,b,c,d,e,f,g,h,i,j,t1,t2,m[64];

  for (i=0,j=0; i < 16; ++i, j += 4)
    m[i] = (data[j] << 24) | (data[j+1] << 16) | (data[j+2] << 8) | (data[j+3]);
  for ( ; i < 64; ++i)
    m[i] = SIG1(m[i-2]) + m[i-7] + SIG0(m[i-15]) + m[i-16];

  a = ctx->state[0];
  b = ctx->state[1];
  c = ctx->state[2];
  d = ctx->state[3];
  e = ctx->state[4];
  f = ctx->state[5];
  g = ctx->state[6];
  h = ctx->state[7];

  for (i = 0; i < 64; ++i) {
    t1 = h + EP1(e) + CH(e,f,g) + sha256_key[i] + m[i];
    t2 = EP0(a) + MAJ(a,b,c);
    h = g;
    g = f;
    f = e;
    e = d + t1;
    d = c;
    c = b;
    b = a;
    a = t1 + t2;
  }

  ctx->state[0] += a;
  ctx->state[1] += b;
  ctx->state[2] += c;
  ctx->state[3] += d;
  ctx->state[4] += e;
  ctx->state[5] += f;
  ctx->state[6] += g;
  ctx->state[7] += h;
}

void sha256_init(SHA256_CTX *ctx) {
  ctx->datalen = 0;
  ctx->bitlen[0] = 0;
  ctx->bitlen[1] = 0;
  ctx->state[0] = 0x6a09e667;
  ctx->state[1] = 0xbb67ae85;
  ctx->state[2] = 0x3c6ef372;
  ctx->state[3] = 0xa54ff53a;
  ctx->state[4] = 0x510e527f;
  ctx->state[5] = 0x9b05688c;
  ctx->state[6] = 0x1f83d9ab;
  ctx->state[7] = 0x5be0cd19;
}

void sha256_update(SHA256_CTX *ctx, uchar *data, uint len) {
  uint t,i;

  for (i=0; i < len; ++i) {
    ctx->data[ctx->datalen] = data[i];
    ctx->datalen++;
    if (ctx->datalen == 64) {
      sha256_transform(ctx,ctx->data);
      DBL_INT_ADD(ctx->bitlen[0],ctx->bitlen[1],512);
      ctx->datalen = 0;
    }
  }
}

void sha256_final(SHA256_CTX *ctx, uchar *hash) {
  uint i;

  i = ctx->datalen;

  // Pad whatever data is left in the buffer.
  if (ctx->datalen < 56) {
    ctx->data[i++] = 0x80;
    while (i < 56)
      ctx->data[i++] = 0x00;
  }
  else {
    ctx->data[i++] = 0x80;
    while (i < 64)
      ctx->data[i++] = 0x00;
    sha256_transform(ctx,ctx->data);
    memset(ctx->data,0,56);
  }

  // Append to the padding the total message's length in bits and transform.
  DBL_INT_ADD(ctx->bitlen[0],ctx->bitlen[1],ctx->datalen * 8);
  ctx->data[63] = ctx->bitlen[0];
  ctx->data[62] = ctx->bitlen[0] >> 8;
  ctx->data[61] = ctx->bitlen[0] >> 16;
  ctx->data[60] = ctx->bitlen[0] >> 24;
  ctx->data[59] = ctx->bitlen[1];
  ctx->data[58] = ctx->bitlen[1] >> 8;
  ctx->data[57] = ctx->bitlen[1] >> 16;
  ctx->data[56] = ctx->bitlen[1] >> 24;
  sha256_transform(ctx,ctx->data);

  // Since this implementation uses little endian byte ordering and SHA uses big endian,
  // reverse all the bytes when copying the final state to the output hash.
  for (i=0; i < 4; ++i) {
    hash[i]    = (ctx->state[0] >> (24-i*8)) & 0x000000ff;
    hash[i+4]  = (ctx->state[1] >> (24-i*8)) & 0x000000ff;
    hash[i+8]  = (ctx->state[2] >> (24-i*8)) & 0x000000ff;
    hash[i+12] = (ctx->state[3] >> (24-i*8)) & 0x000000ff;
    hash[i+16] = (ctx->state[4] >> (24-i*8)) & 0x000000ff;
    hash[i+20] = (ctx->state[5] >> (24-i*8)) & 0x000000ff;
    hash[i+24] = (ctx->state[6] >> (24-i*8)) & 0x000000ff;
    hash[i+28] = (ctx->state[7] >> (24-i*8)) & 0x000000ff;
  }
}

void compute(struct In* input, struct Out* output){
  SHA256_CTX ctx;
  unsigned char text1[3] = {"abc"};
  unsigned char buf[32];
  int i;

  sha256_init(&ctx);
  sha256_update(&ctx, text1, 3);
  sha256_final(&ctx, buf);

  for (i = 0; i < 32; i++) {
    output->buf[i] = buf[i];
  }

  output->valid = 1;

  return output->valid;
}
```

**Comment by cnasikas** [comment]
And for: https://github.com/B-Con/crypto-algorithms/blob/master/sha256.c

```
#define SHA256_BLOCK_SIZE 32            // SHA256 outputs a 32 byte digest

/**************************** DATA TYPES ****************************/
typedef unsigned char BYTE;             // 8-bit byte
typedef unsigned int  WORD;             // 32-bit word, change to "long" for 16-bit machines

typedef struct {
	BYTE data[64];
	WORD datalen;
	unsigned long long bitlen;
	WORD state[8];
} SHA256_CTX;

struct In {
  int in;
};

struct Out {
  int valid;
  unsigned char buf[32];
};

/*********************** FUNCTION DECLARATIONS **********************/
void sha256_init(SHA256_CTX *ctx);
void sha256_update(SHA256_CTX *ctx, BYTE *data, unsigned int len);
void sha256_final(SHA256_CTX *ctx, BYTE *hash);

#define ROTLEFT(a,b) (((a) << (b)) | ((a) >> (32-(b))))
#define ROTRIGHT(a,b) (((a) >> (b)) | ((a) << (32-(b))))

#define CH(x,y,z) (((x) & (y)) ^ (~(x) & (z)))
#define MAJ(x,y,z) (((x) & (y)) ^ ((x) & (z)) ^ ((y) & (z)))
#define EP0(x) (ROTRIGHT(x,2) ^ ROTRIGHT(x,13) ^ ROTRIGHT(x,22))
#define EP1(x) (ROTRIGHT(x,6) ^ ROTRIGHT(x,11) ^ ROTRIGHT(x,25))
#define SIG0(x) (ROTRIGHT(x,7) ^ ROTRIGHT(x,18) ^ ((x) >> 3))
#define SIG1(x) (ROTRIGHT(x,17) ^ ROTRIGHT(x,19) ^ ((x) >> 10))

static const WORD k[64] = {
	0x428a2f98,0x71374491,0xb5c0fbcf,0xe9b5dba5,0x3956c25b,0x59f111f1,0x923f82a4,0xab1c5ed5,
	0xd807aa98,0x12835b01,0x243185be,0x550c7dc3,0x72be5d74,0x80deb1fe,0x9bdc06a7,0xc19bf174,
	0xe49b69c1,0xefbe4786,0x0fc19dc6,0x240ca1cc,0x2de92c6f,0x4a7484aa,0x5cb0a9dc,0x76f988da,
	0x983e5152,0xa831c66d,0xb00327c8,0xbf597fc7,0xc6e00bf3,0xd5a79147,0x06ca6351,0x14292967,
	0x27b70a85,0x2e1b2138,0x4d2c6dfc,0x53380d13,0x650a7354,0x766a0abb,0x81c2c92e,0x92722c85,
	0xa2bfe8a1,0xa81a664b,0xc24b8b70,0xc76c51a3,0xd192e819,0xd6990624,0xf40e3585,0x106aa070,
	0x19a4c116,0x1e376c08,0x2748774c,0x34b0bcb5,0x391c0cb3,0x4ed8aa4a,0x5b9cca4f,0x682e6ff3,
	0x748f82ee,0x78a5636f,0x84c87814,0x8cc70208,0x90befffa,0xa4506ceb,0xbef9a3f7,0xc67178f2
};

void sha256_transform(SHA256_CTX *ctx, BYTE *data)
{
	WORD a, b, c, d, e, f, g, h, i, j, t1, t2, m[64];

	for (i = 0, j = 0; i < 16; ++i, j += 4)
		m[i] = (data[j] << 24) | (data[j + 1] << 16) | (data[j + 2] << 8) | (data[j + 3]);
	for ( ; i < 64; ++i)
		m[i] = SIG1(m[i - 2]) + m[i - 7] + SIG0(m[i - 15]) + m[i - 16];

	a = ctx->state[0];
	b = ctx->state[1];
	c = ctx->state[2];
	d = ctx->state[3];
	e = ctx->state[4];
	f = ctx->state[5];
	g = ctx->state[6];
	h = ctx->state[7];

	for (i = 0; i < 64; ++i) {
		t1 = h + EP1(e) + CH(e,f,g) + k[i] + m[i];
		t2 = EP0(a) + MAJ(a,b,c);
		h = g;
		g = f;
		f = e;
		e = d + t1;
		d = c;
		c = b;
		b = a;
		a = t1 + t2;
	}

	ctx->state[0] += a;
	ctx->state[1] += b;
	ctx->state[2] += c;
	ctx->state[3] += d;
	ctx->state[4] += e;
	ctx->state[5] += f;
	ctx->state[6] += g;
	ctx->state[7] += h;
}

void sha256_init(SHA256_CTX *ctx)
{
	ctx->datalen = 0;
	ctx->bitlen = 0;
	ctx->state[0] = 0x6a09e667;
	ctx->state[1] = 0xbb67ae85;
	ctx->state[2] = 0x3c6ef372;
	ctx->state[3] = 0xa54ff53a;
	ctx->state[4] = 0x510e527f;
	ctx->state[5] = 0x9b05688c;
	ctx->state[6] = 0x1f83d9ab;
	ctx->state[7] = 0x5be0cd19;
}

void sha256_update(SHA256_CTX *ctx, BYTE *data, unsigned int len)
{
	WORD i;

	for (i = 0; i < len; ++i) {
		ctx->data[ctx->datalen] = data[i];
		ctx->datalen++;
		if (ctx->datalen == 64) {
			sha256_transform(ctx, ctx->data);
			ctx->bitlen += 512;
			ctx->datalen = 0;
		}
	}
}

void sha256_final(SHA256_CTX *ctx, BYTE *hash)
{
	WORD i;

	i = ctx->datalen;

	// Pad whatever data is left in the buffer.
	if (ctx->datalen < 56) {
		ctx->data[i++] = 0x80;
		while (i < 56)
			ctx->data[i++] = 0x00;
	}
	else {
		ctx->data[i++] = 0x80;
		while (i < 64)
			ctx->data[i++] = 0x00;
		sha256_transform(ctx, ctx->data);
		memset(ctx->data, 0, 56);
	}

	// Append to the padding the total message's length in bits and transform.
	ctx->bitlen += ctx->datalen * 8;
	ctx->data[63] = ctx->bitlen;
	ctx->data[62] = ctx->bitlen >> 8;
	ctx->data[61] = ctx->bitlen >> 16;
	ctx->data[60] = ctx->bitlen >> 24;
	ctx->data[59] = ctx->bitlen >> 32;
	ctx->data[58] = ctx->bitlen >> 40;
	ctx->data[57] = ctx->bitlen >> 48;
	ctx->data[56] = ctx->bitlen >> 56;
	sha256_transform(ctx, ctx->data);

	// Since this implementation uses little endian byte ordering and SHA uses big endian,
	// reverse all the bytes when copying the final state to the output hash.
	for (i = 0; i < 4; ++i) {
		hash[i]      = (ctx->state[0] >> (24 - i * 8)) & 0x000000ff;
		hash[i + 4]  = (ctx->state[1] >> (24 - i * 8)) & 0x000000ff;
		hash[i + 8]  = (ctx->state[2] >> (24 - i * 8)) & 0x000000ff;
		hash[i + 12] = (ctx->state[3] >> (24 - i * 8)) & 0x000000ff;
		hash[i + 16] = (ctx->state[4] >> (24 - i * 8)) & 0x000000ff;
		hash[i + 20] = (ctx->state[5] >> (24 - i * 8)) & 0x000000ff;
		hash[i + 24] = (ctx->state[6] >> (24 - i * 8)) & 0x000000ff;
		hash[i + 28] = (ctx->state[7] >> (24 - i * 8)) & 0x000000ff;
	}
}

void compute(struct In* input, struct Out* output){
  SHA256_CTX ctx;
  unsigned char text1[4] = {"abcd"};
  unsigned char buf[32];
  int i;

  sha256_init(&ctx);
  sha256_update(&ctx, text1, 4);
  sha256_final(&ctx, buf);

  output->buf = buf;
  output->valid = 1;

  return output->valid;
}

```

**Comment by cnasikas** [comment]
One problem I notice is that the two implementations above outputs different value for the same input "abcd"

Could anyone tell what is wrong or find any mistakes in the code? I can not guarantee is secure or correct. I just change the code a little so it can be compiled with pepper.

**Comment by cnasikas** [comment]
I made some experiments to understand better how the input is being handled. The input to be treated as string should be `char unsigned char *data` and is in alignment with OpenSSL and NodeJS. 

**Experiments:**

```
File contains: abcd

NodeJS SHA256:  fc4b5fd6816f75a7c81fc8eaa9499d6a299bd803397166e8c4cf9280b801d62c
OpenSSL SHA256: fc4b5fd6816f75a7c81fc8eaa9499d6a299bd803397166e8c4cf9280b801d62c

/* Text: "abcd": Same as char unsigned char *data */
/* OpenSSL: echo -n abcd | sha256sum */

NodeJS SHA256:   88d4266fd4e6338d13b845fcf289579d209c897823b9217da3e161936f031589
OpenSSL SHA256:  88d4266fd4e6338d13b845fcf289579d209c897823b9217da3e161936f031589
SJCL SHA256:     88d4266fd4e6338d13b845fcf289579d209c897823b9217da3e161936f031589

/* SHA256 as: char unsigned char data[4] = {"abcd"} */

ZKP SHA256:     48067E197DF6CA9EED62EDCC400EC9B1EE906CC6D5EA25C96BA4C2E297C6649C

/* SHA256 as: char unsigned char *data */
/* correct */

ZKP SHA256:     88D4266FD4E6338D13B845FCF289579D209C897823B9217DA3E161936F031589

/* SHA256 as: unsigned char data[4] = {"a", "b", "c", "d"}; */

ZKP SHA256:     ED8B7FF855403150F0DA9DEECC354027316A554BB7096708290C25E78331C561

/* SHA256 as: unsigned char data[4] = "abcd"; */

ZKP SHA256:     D3FE97979D0FBE3BF464E5001637443D72B890242A801CC221B1C8A169A69761

```

**Comment by maxhowald** [comment]
Thanks for running those experiments! I'm not exactly sure why you're getting different results based on the specific way the type of the input is declared. 

One question is, what happens when you run the experiments using a regular C compiler? Specifically, do you get the same or different results if you replace the `compute` function in the examples you posted with a `main` function, and compile it with `gcc --std=c89`?

**Comment by cnasikas** [comment]
When I run the experiments using a regular C compiler, with `gcc --std=c89`, I get the same results for all types.
I thank you for this amazing framework!

One mistake I made that I realized it after compiling with gcc was that `unsigned char data[4] = {"a", "b", "c", "d"};` raise an error. It should be `unsigned char data[4] = {'a', 'b', 'c', 'd'};`. Double quotes `" "` vs single quote `' '`. The first one is a string and the second a char. So I fix it and I tried again with pepper and it gave a correct output.

### **Summarization**:

**Pepper:**

1. unsigned char data[4] = {"abcd"}; -- Wrong

1. unsigned char *data = "abcd"; -- Correct

1. unsigned char data[4] = {'a', 'b', 'c', 'd'}; -- Correct

1. unsigned char data[4] = "abcd"; -- Wrong

**GCC (without pepper):**

1. unsigned char data[4] = {"abcd"}; -- Correct

1. unsigned char *data = "abcd"; -- Correct

1. unsigned char data[4] = {'a', 'b', 'c', 'd'}; -- Correct

1. unsigned char data[4] = "abcd"; -- Correct

**Comment by maxhowald** [comment]
Thanks again for reporting these results! It looks like this is a deficiency in our C compiler not allowing the coercion of character strings to character arrays during assignment. 

We may implement a fix for this eventually, but hopefully the workaround you found works for now! Please let us know if you have any further questions or issues.
