### ISSUE TITLE
how to increase parser placeholder

### ISSUE THREAD

**Issue by thomaslavaur** [pepper-project/pequin#68]
Hello I had this error today and in can't figure it out where is the problem. I tried to use my own implementation of memcpy and I think the problem is here.

Here is my error : 

Exception in thread "main" java.lang.RuntimeException: Error: Parser reached placeholder implementation of parse tree action. 
	at ccomp.parser.CParser$152.reduce(CParser.java:1330)
	at ccomp.parser.CParser.invokeReduceAction(CParser.java:1763)
	at beaver.Parser.reduce(Parser.java:464)
	at beaver.Parser.parse(Parser.java:383)
	at beaver.Parser.parse(Parser.java:352)
	at ccomp.parser_hw.CCompiler.compileProgram(CCompiler.java:169)
	at zcc.ZCC.compile(ZCC.java:230)
	at zcc.ZCC.main(ZCC.java:127)
Makefile:113: recipe for target 'bin/test.params' failed
make: *** [bin/test.params] Error 1

**Comment by noresistence** [comment]
This means that you tried to use a feature of the language that is not supported by the compiler.

Try to reduce your code until you have a minimal working example that still produces this error message. This could already tell you the source of the problem, and you could post it here to provide additional information.
